import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Brain, Check, CheckCircle2, Clock3, Languages, RotateCcw, Search, Sparkles, X } from "lucide-react";
import { api } from "./api";
import { Badge, Button, Card, Empty, ErrorState, Progress, Skeleton } from "./ui";

type VocabularyItem={id:string;term:string;definition:string;simple_definition:string;native_explanation:string;examples:string[];collocations:string[];common_mistakes:string[];cefr:string;due:boolean;repetitions:number;interval_days:number;due_at:string};
type ReviewResult={term:string;recall_correct:boolean;context_correct:boolean;quality:number;feedback:string;correct_answer:string;example:string;repetitions:number;interval_days:number;due_at:string};
type Phase="learn"|"recall"|"context"|"result";

export function VocabularyLearningPage(){
  const client=useQueryClient();
  const [queryText,setQueryText]=useState("");
  const [word,setWord]=useState<VocabularyItem|null>(null);
  const [phase,setPhase]=useState<Phase>("learn");
  const [recall,setRecall]=useState("");
  const [sentence,setSentence]=useState("");
  const [result,setResult]=useState<ReviewResult|null>(null);
  const query=useQuery({queryKey:["vocabulary",queryText],queryFn:()=>api<{items:VocabularyItem[]}>(`/vocabulary?q=${encodeURIComponent(queryText)}`)});
  const review=useMutation({
    mutationFn:()=>api<ReviewResult>(`/vocabulary/${word!.id}/review`,{method:"POST",body:JSON.stringify({recall_answer:recall,context_sentence:sentence})}),
    onSuccess:data=>{setResult(data);setPhase("result");client.invalidateQueries({queryKey:["vocabulary"]});client.invalidateQueries({queryKey:["dashboard"]});client.invalidateQueries({queryKey:["progress"]});},
  });
  const items=query.data?.items??[];
  const due=items.filter(item=>item.due);
  const studied=items.filter(item=>item.repetitions>0).length;
  const begin=(item:VocabularyItem)=>{setWord(item);setPhase("learn");setRecall("");setSentence("");setResult(null);review.reset();};
  const next=()=>{const candidate=items.find(item=>item.id!==word?.id&&item.due)??items.find(item=>item.id!==word?.id);candidate?begin(candidate):setWord(null);};
  const close=()=>{setWord(null);setResult(null);review.reset();};

  return <>
    <div className="vocab-page-title"><div><p className="eyebrow">Your technical lexicon</p><h1>Vocabulary lab</h1><p>Learn the meaning, recall the term, then use it in a real engineering sentence.</p></div><Button onClick={()=>due[0]&&begin(due[0])} disabled={!due.length}><Brain/>Review {due.length} due</Button></div>
    <div className="vocab-stats"><Card><Clock3/><div><strong>{due.length}</strong><span>due now</span></div></Card><Card><CheckCircle2/><div><strong>{studied}</strong><span>words practised</span></div></Card><Card><Sparkles/><div><strong>{items.reduce((sum,item)=>sum+item.repetitions,0)}</strong><span>successful recalls</span></div></Card></div>
    <div className="toolbar"><div className="search"><Search/><input value={queryText} onChange={event=>setQueryText(event.target.value)} placeholder="Search technical vocabulary…"/></div><div className="tabs"><button className={!queryText?"active":""} onClick={()=>setQueryText("")}>All terms</button><button onClick={()=>setQueryText("deploy")}>Deployment</button><button onClick={()=>setQueryText("API")}>API</button></div></div>
    {query.isLoading?<div className="vocab-grid"><Skeleton className="tall"/><Skeleton className="tall"/><Skeleton className="tall"/></div>:query.error?<ErrorState message={query.error.message}/>:!items.length?<Empty icon={<Languages/>} title="No terms found" description="Try a broader search."/>:<div className="vocab-grid">{items.map(item=><Card key={item.id} className="vocab-card vocab-learning-card" onClick={()=>begin(item)}><div><Badge tone={item.due?"amber":"green"}>{item.due?"Due now":`In ${item.interval_days}d`}</Badge><button aria-label={`Study ${item.term}`}><ArrowRight/></button></div><h2>{item.term}</h2><p>{item.simple_definition}</p><div className="collocation"><small>COMMON COLLOCATION</small><span>{item.collocations[0]}</span></div><footer><span>{item.repetitions?`${item.repetitions} successful reviews`:"New term"}</span><span>{item.cefr}</span></footer></Card>)}</div>}
    {word&&<div className="modal-backdrop vocabulary-trainer-backdrop"><Card className="vocabulary-trainer"><button className="modal-close" onClick={close} aria-label="Close vocabulary practice"><X/></button><div className="trainer-progress"><span>Vocabulary practice</span><span>{phase==="learn"?"1":phase==="recall"?"2":phase==="context"?"3":"4"} / 4</span></div><Progress value={phase==="learn"?25:phase==="recall"?50:phase==="context"?75:100}/>
      {phase==="learn"&&<section><Badge tone="blue">LEARN</Badge><h1>{word.term}</h1><p className="trainer-definition">{word.definition}</p><div className="trainer-two-columns"><div><small>IN SIMPLE ENGLISH</small><p>{word.simple_definition}</p></div><div><small>ПОЯСНЕНИЕ</small><p>{word.native_explanation}</p></div></div><div className="modal-section"><small>USEFUL COLLOCATIONS</small>{word.collocations.map(item=><span key={item}><Check/> {item}</span>)}</div><blockquote>“{word.examples[0]}”</blockquote>{word.common_mistakes.length>0&&<div className="trainer-warning"><b>Common mistake</b><span>{word.common_mistakes[0]}</span></div>}<Button onClick={()=>setPhase("recall")}>I’m ready to recall<ArrowRight/></Button></section>}
      {phase==="recall"&&<section><Badge tone="amber">RECALL</Badge><h2>Which technical term matches this meaning?</h2><Card className="recall-prompt"><Languages/><p>{word.simple_definition}</p><small>{word.collocations[0]?.replace(new RegExp(word.term,"ig"),"____")}</small></Card><label className="trainer-input"><span>Your answer</span><input autoFocus value={recall} onChange={event=>setRecall(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&recall.trim())setPhase("context")}} placeholder="Type the term from memory…"/></label><div className="trainer-actions"><Button variant="ghost" onClick={()=>setPhase("learn")}><ArrowLeft/>Review card</Button><Button disabled={!recall.trim()} onClick={()=>setPhase("context")}>Use in context<ArrowRight/></Button></div></section>}
      {phase==="context"&&<section><Badge tone="green">USE IN CONTEXT</Badge><h2>Write a real engineering sentence with “{word.term}”</h2><p>Show that you understand the meaning. Include a system, problem, action, or result.</p><div className="context-prompts"><button onClick={()=>setSentence(`We used ${word.term} to improve the reliability of our API.`)}>API reliability</button><button onClick={()=>setSentence(`The main ${word.term} affected our production performance.`)}>Production issue</button></div><label className="trainer-input"><span>Your contextual sentence</span><textarea autoFocus rows={5} value={sentence} onChange={event=>setSentence(event.target.value)} placeholder={`Example: We identified ${word.term} while profiling the API…`}/><small>{sentence.trim().split(/\s+/).filter(Boolean).length} words · aim for at least 6</small></label>{review.error&&<div className="form-error">{review.error.message}</div>}<div className="trainer-actions"><Button variant="ghost" onClick={()=>setPhase("recall")}><ArrowLeft/>Back</Button><Button loading={review.isPending} disabled={sentence.trim().length<3} onClick={()=>review.mutate()}>Check and schedule<Check/></Button></div></section>}
      {phase==="result"&&result&&<section className="review-result"><span className={result.recall_correct&&result.context_correct?"result-icon success":"result-icon retry"}>{result.recall_correct&&result.context_correct?<CheckCircle2/>:<RotateCcw/>}</span><Badge tone={result.recall_correct&&result.context_correct?"green":"amber"}>{result.recall_correct&&result.context_correct?"REVIEW COMPLETE":"KEEP PRACTISING"}</Badge><h2>{result.recall_correct&&result.context_correct?"You recalled and applied the word.":"Useful attempt — review the pattern."}</h2><div className="result-checks"><div><span>{result.recall_correct?<CheckCircle2/>:<X/>}</span><div><b>Recall</b><p>{result.recall_correct?`Correct: ${result.term}`:`The answer was “${result.correct_answer}”.`}</p></div></div><div><span>{result.context_correct?<CheckCircle2/>:<X/>}</span><div><b>Context</b><p>{result.feedback}</p></div></div></div><blockquote>Model example: “{result.example}”</blockquote><p className="next-review">{result.quality>=3?`Next review in ${result.interval_days} day${result.interval_days===1?"":"s"}.`:"This word returns to your queue in 10 minutes."}</p><div className="trainer-actions"><Button variant="ghost" onClick={()=>begin(word)}><RotateCcw/>Practise again</Button><Button onClick={next}>Next word<ArrowRight/></Button></div></section>}
    </Card></div>}
  </>;
}
